Enable install under proxy
mtlynch/ansible-role-tinypilot pull request #72
Opened 2021-01-09 19:09 UTC by yamato225

To install TinyPilot using proxy, I added "extra_args" on "create TinyPilot virtualenv" step.

When I tried to install using proxy, this step failed because pip command can't verify SSL certification.
I could solve this problem by adding "--trusted-host pypi.org" arguments on this step.

But it's not good for the user who doesn't use proxy, so I use pip_args variable.
If the user want to use proxy, pip_args is "--trusted-host pypi.org".
If not, `pip_args` is empty text.

pip_args is setten by quick-install.

Related: https://github.com/mtlynch/tinypilot/pull/402

2021-01-13 22:30 UTC, mtlynch requested changes

2021-01-13 22:30 UTC, mtlynch commented on defaults/main.yml
> +pip_args: ""
Can we make this `tinypilot_pip_args` for consistency and leave a trailing newline?

2021-01-14 15:37 UTC, yamato225 commented
Sure. I changed `pip_args` to `tinypilot_pip_args`.

2021-01-14 16:00 UTC, mtlynch commented
Thanks!

2021-01-14 16:00 UTC, merged