Add silent mode to collect-debug-logs
mtlynch/ansible-role-tinypilot pull request #82
Opened 2021-01-22 21:55 UTC by invrainbow

Closes https://github.com/mtlynch/ansible-role-tinypilot/issues/81.

 * Add a parser for command-line options
 * Add a help description (now that the script has options)
 * Respect -q/-u when determining if we should upload logs or not

2021-01-22 22:06 UTC, mtlynch requested changes
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/82)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @invrainbow)

___
*[files/collect-debug-logs, line 13 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/82#-MRg7JzM9RY4V9qFAIsp:-MRg7JzN2XWuoWfk47Te:b-9i2xrn) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/50090b9ca08bdc0df8c4728444634f0e508a7315/files/collect-debug-logs#L13)):*
> ```
>     -h Display this help and exit.
>     -q Run in silent mode without prompting user for inputs.
>     -u In silent mode, upload log file. If -q is provided and -u is not, the log file will not be uploaded.
> ```

We can drop this. I don't think we'll need it, and I'd rather avoid any added complexity.
___
*[files/collect-debug-logs, line 22 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-tinypilot/82#-MRg7A3rCavPM9YpFOuI:-MRg7A3s4Yb6tH4gJZi-:b97xa0i) ([raw file](https://github.com/mtlynch/ansible-role-tinypilot/blob/50090b9ca08bdc0df8c4728444634f0e508a7315/files/collect-debug-logs#L22)):*
> ```
> 
> # Parse command-line arguments.
> while getopts "hqu" opt; do
> ```

(no action required): This is cool! I've never used getopts.


<!-- Sent from Reviewable.io -->

2021-01-22 22:07 UTC, invrainbow commented
To clarify, do you mean we can drop the `-u` flag, or the help menu?
If the former, should we always default to not uploading the log file in silent mode?

2021-01-22 22:40 UTC, mtlynch commented
>To clarify, do you mean we can drop the -u flag, or the help text?

We can drop the `-u` flag and auto-upload functionality. 

>If the former, should we always default to not uploading the log file in silent mode?

Right, if the user passes `-q`, we can assume no upload.

2021-01-25 19:22 UTC, invrainbow commented
@mtlynch Made requested changes.

2021-01-25 19:53 UTC, mtlynch commented
LGTM, thanks!

2021-01-25 19:53 UTC, merged